name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Maven release
      uses: qcastel/github-actions-maven-release@v1.0.2
      with:
        # Filter the branch to execute the release on
        release-branch-name: "master"
        # The git user name for commiting the release
        git-release-bot-name: "Unikaz"
        # The git user email for commiting the release
        git-release-bot-email: "unikaz@free.fr"
        # Github access token. https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
        access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
